# Generated by Django 3.2.19 on 2023-07-19 17:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dylanp400/image/upload/f_auto,q_auto/sample', max_length=255, verbose_name='image'),
        ),
    ]
