# Generated by Django 3.2.19 on 2023-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230723_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
