# Generated by Django 3.2.19 on 2023-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='rating',
            field=models.TextField(),
        ),
    ]
