# Generated by Django 3.2.19 on 2023-07-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usertestimonial_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestimonial',
            name='service',
            field=models.CharField(choices=[('select', 'Select'), ('Barber', 'Barber'), ('tattoo artist', 'Tattoo Artist'), ('Piercer', 'Piercer')], max_length=20),
        ),
    ]
