# Generated by Django 3.2.19 on 2023-07-31 23:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tattooservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
