# Generated by Django 3.2.19 on 2023-07-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usertestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestimonial',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.teammembers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertestimonial',
            name='service',
            field=models.CharField(choices=[('Select', 'Select'), ('barber', 'Barber'), ('tattoo_artist', 'Tattoo Artist')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')]),
        ),
    ]
