# Generated by Django 3.2.19 on 2023-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230714_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestimonial',
            name='service',
            field=models.CharField(choices=[('select', 'Select'), ('Barber', 'Barber'), ('tattoo_artist', 'Tattoo Artist')], max_length=20),
        ),
    ]
