# Generated by Django 3.2.19 on 2023-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_barbermembers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='service',
            field=models.CharField(choices=[('Barber', 'Barber'), ('tattoo artist', 'Tattoo Artist'), ('Piercer', 'Piercer')], max_length=20),
        ),
    ]
